name: build-macos

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        run: npm run build:web

      - name: Build Tauri (macOS .app)
        run: npx tauri build

      - name: Package .app as zip artifact
        run: |
          mkdir -p out
          APP_PATH=$(ls -d src-tauri/target/release/bundle/macos/*.app | head -n 1)
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" out/OfflineFinder-macOS-app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: out/OfflineFinder-macOS-app.zip
